services:
  redpanda1:
    image: redpandadata/redpanda:latest
    container_name: redpanda1
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --overprovisioned
      - --node-id 1
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://localhost:9093
    ports:
      - "9093:9092"

  redpanda2:
    image: redpandadata/redpanda:latest
    container_name: redpanda2
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --overprovisioned
      - --node-id 2
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://localhost:9094
    ports:
      - "9094:9092"

  redpanda3:
    image: redpandadata/redpanda:latest
    container_name: redpanda3
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --overprovisioned
      - --node-id 3
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://localhost:9095
    ports:
      - "9095:9092"
